import type { Metadata } from "next";
import styles from "../legal.module.css";

export const metadata: Metadata = { title: "Terms of Service — Cocomo" };

export default function TermsPage() {
  return (
    <div className={styles.page}>
      <div className="container">
        <h1 className={styles.heading}>Terms of Service</h1>
        <p className={styles.updated}>Last updated: July 2026</p>
        <div className={styles.body}>
          <h2>1. Service Description</h2>
          <p>
            Cocomo provides a software-enabled Growth Operating System designed to ingest merchant transaction metrics, analyze growth signals, and recommend campaigns. The software platform is free to connect. Cocomo is compensated solely through a pre-agreed percentage of incremental revenue demonstrably generated by campaigns launched directly through the platform.
          </p>
          <h2>2. Acceptable Use</h2>
          <p>
            You agree to provide accurate, complete, and current transaction baseline information. You may not upload mock transaction data, run reverse-engineering tools on the Engine pipeline, or utilize Cocomo Media connections to distribute content that violates local advertising regulations or creator guidelines.
          </p>
          <h2>3. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Cocomo and its founders shall not be liable for any indirect, incidental, or consequential damages resulting from campaign execution decisions, POS connectivity interruptions, or creator campaign delays. All recommendations are advisory, and ultimate execution approval rests solely with the merchant.
          </p>
          <h2>4. Termination</h2>
          <p>
            You can disconnect your POS integration and close your merchant profile at any time. Compensation agreements for already active campaigns will continue to accrue until the specific campaign attribution window expires.
          </p>
          <h2>5. Contact</h2>
          <p>Legal questions: <a href="mailto:legal@cocomo.com">legal@cocomo.com</a></p>
        </div>
      </div>
    </div>
  );
}
