"use client";

import React, { Suspense, useRef } from "react";
import dynamic from "next/dynamic";
import { motion, useScroll, useTransform } from "framer-motion";
import Link from "next/link";
import { Loop } from "../sections/Loop";
import { Cpu, Eye, Zap, BarChart4, Database, TrendingUp, Sparkles, MessageSquare, ArrowRight, ShieldCheck, Lock, Database as Db } from "lucide-react";
import styles from "./platform.module.css";

const EnginePipelineCanvas = dynamic(
  () => import("@/components/media/EnginePipelineCanvas").then((m) => m.EnginePipelineCanvas),
  {
    ssr: false,
    loading: () => (
      <div className={styles.pipeline__fallback} aria-hidden="true">
        <div className={styles.pipeline__static} />
      </div>
    ),
  }
);

const phases = [
  {
    num: "01",
    title: "Observe Signals",
    icon: Eye,
    body: "Cocomo Engine connects directly to your Point of Sale system, foot-traffic telemetry, Meta ad accounts, Google reviews, and local weather indices. It observes hourly sales data, repeat visit cycles, and competitive pricing dynamically.",
    statVal: "POS & Ads",
    statLabel: "Real-time Connectors",
    color: "#2563EB"
  },
  {
    num: "02",
    title: "Recommend Actions",
    icon: Cpu,
    body: "Instead of raw charts, our intelligence layers rank growth opportunities by projected ₹ impact, execution difficulty, and statistical confidence. You get clear, plainspoken recommendations for your outlet.",
    statVal: "AI Ranked",
    statLabel: "Revenue Recommendations",
    color: "#0EA5E9"
  },
  {
    num: "03",
    title: "Execute Seamlessly",
    icon: Zap,
    body: "One click triggers campaign execution. The engine orchestrates creators (via Cocomo Media), launches hyper-local Meta ad sets, pushes tailored WhatsApp re-engagement loops, or triggers internal staff task workflows automatically.",
    statVal: "1-Click",
    statLabel: "Execution Dispatch",
    color: "#2563EB"
  },
  {
    num: "04",
    title: "Measure Impact",
    icon: BarChart4,
    body: "No vanity metrics or estimated impressions. Every campaign is tracked back to outlet-level transactions. We prove the exact incremental revenue lift generated by each recommendation.",
    statVal: "₹ Verified",
    statLabel: "Transaction-level Lift",
    color: "#0EA5E9"
  },
];

const integrations = [
  { icon: "🧾", name: "Petpooja", desc: "Full POS integration" },
  { icon: "💳", name: "Pine Labs", desc: "Payment telemetry" },
  { icon: "📱", name: "Meta Ads", desc: "Campaign automation" },
  { icon: "💬", name: "WhatsApp", desc: "Loyalty loops" },
  { icon: "⭐", name: "Google", desc: "Reviews & local" },
  { icon: "📊", name: "Swiggy", desc: "Delivery analytics" },
  { icon: "🍽️", name: "Zomato", desc: "Platform data" },
  { icon: "🌡️", name: "Weather", desc: "Demand correlation" },
];

interface StackPhaseCardProps {
  num: string;
  title: string;
  body: string;
  icon: React.ComponentType<{ size: number; color?: string }>;
  statVal: string;
  statLabel: string;
  color: string;
  index: number;
}

function StackPhaseCard({ num, title, body, icon: Icon, statVal, statLabel, color, index }: StackPhaseCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: cardRef,
    offset: ["start end", "start 110px"]
  });

  const scale = useTransform(scrollYProgress, [0.5, 1], [1, 1 - index * 0.025]);
  const opacity = useTransform(scrollYProgress, [0.5, 1], [1, 1 - index * 0.08]);

  return (
    <motion.div
      ref={cardRef}
      className={styles.phaseCard}
      style={{ scale, opacity }}
    >
      {/* Color top border */}
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: "2px", background: `linear-gradient(90deg, ${color}, ${color}88)` }} />

      <div className={styles.phaseCard__content}>
        <div className={styles.phaseCard__left}>
          <div className={styles.phaseCard__header}>
            <span className={styles.phaseCard__num} style={{ color }}>{num}</span>
            <div className={styles.phaseCard__iconWrap} style={{ background: `${color}10`, borderColor: `${color}30` }}>
              <Icon size={20} color={color} />
            </div>
          </div>
          <h3 className={styles.phaseCard__title}>{title}</h3>
          <p className={styles.phaseCard__body}>{body}</p>
        </div>

        <div className={styles.phaseCard__right}>
          <div className={styles.phaseCard__stat}>
            <span className={styles.phaseCard__statVal} style={{ color }}>{statVal}</span>
            <span className={styles.phaseCard__statLabel}>{statLabel}</span>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

export default function PlatformPage() {
  return (
    <div className={styles.page}>
      {/* ── Hero ── */}
      <section className={styles.hero} aria-labelledby="platform-heading">
        <div className={styles.hero__bg}>
          <img src="/platform-bg.png" className={styles.hero__bgImage} alt="" aria-hidden="true" />
          <div className={styles.hero__bgFade} />
        </div>
        <div className={styles.hero__bloomLeft} />

        <div className={`container ${styles.hero__inner}`}>
          <motion.div
            className={styles.hero__eyebrow}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          >
            <Cpu size={11} />
            COCOMO ENGINE PLATFORM
          </motion.div>

          <h1 id="platform-heading" className={styles.hero__heading}>
            <motion.span
              style={{ display: "block" }}
              initial={{ opacity: 0, y: 40, filter: "blur(6px)" }}
              animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              transition={{ delay: 0.1, duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
            >
              A growth engine,
            </motion.span>
            <motion.em
              className={styles.hero__em}
              initial={{ opacity: 0, y: 40, filter: "blur(6px)" }}
              animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              transition={{ delay: 0.22, duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
            >
              not a dashboard.
            </motion.em>
          </h1>

          <motion.p
            className={styles.hero__sub}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.45, duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
          >
            Cocomo Engine is the missing growth layer. It continuously connects POS telemetry to real-world creator campaigns and digital advertising actions, delivering verifiable revenue lift.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6, duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          >
            <Link href="/demo" className={styles.hero__cta} id="platform-cta">
              Book a demo — free to start
              <ArrowRight size={16} strokeWidth={2} />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ── Pipeline canvas ── */}
      <section className={styles.pipeline} aria-labelledby="pipeline-heading">
        <div className="container">
          <div className={styles.pipeline__header}>
            <span className="eyebrow">Live Data Pipeline</span>
            <h2 id="pipeline-heading" className={styles.pipeline__heading}>
              From signal to action in real time.
            </h2>
            <p className={styles.pipeline__sub}>
              Watch the engine process your POS signals, match them to growth patterns, and dispatch campaigns automatically.
            </p>
          </div>
          <div className={styles.pipeline__canvas}>
            <Suspense fallback={null}>
              <EnginePipelineCanvas />
            </Suspense>
          </div>
        </div>
      </section>

      {/* ── Loop diagram ── */}
      <Loop />

      {/* ── Four phases stacking ── */}
      <section id="phases" className={styles.phases} aria-labelledby="phases-heading">
        <div className="container">
          <div className={styles.phases__header}>
            <span className="eyebrow">Product Pipeline</span>
            <h2 id="phases-heading" className={styles.phases__heading}>
              Continuous closed-loop growth.
            </h2>
            <p className={styles.phases__sub}>Scroll to see each phase of the engine in action.</p>
          </div>

          <div className={styles.phases__list}>
            {phases.map((phase, idx) => (
              <StackPhaseCard
                key={phase.num}
                num={phase.num}
                title={phase.title}
                body={phase.body}
                icon={phase.icon}
                statVal={phase.statVal}
                statLabel={phase.statLabel}
                color={phase.color}
                index={idx}
              />
            ))}
          </div>
        </div>
      </section>

      {/* ── Integrations ── */}
      <section id="integrations" className={styles.integrations} aria-labelledby="integrations-heading">
        <div className="container">
          <div className={styles.integrations__header}>
            <span className="eyebrow">Integrations</span>
            <h2 id="integrations-heading" className={styles.integrations__heading}>
              Works with your existing stack.
            </h2>
            <p className={styles.integrations__sub}>
              Cocomo connects seamlessly to the tools you already use — no rip-and-replace required.
            </p>
          </div>
          <div className={styles.integrations__grid}>
            {integrations.map((item) => (
              <motion.div
                key={item.name}
                className={styles.integrations__card}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              >
                <div className={styles.integrations__cardIcon}>{item.icon}</div>
                <div className={styles.integrations__cardName}>{item.name}</div>
                <div className={styles.integrations__cardDesc}>{item.desc}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Security ── */}
      <section id="security" className={styles.pipeline} aria-labelledby="security-heading">
        <div className="container">
          <div className={styles.pipeline__header}>
            <span className="eyebrow">Enterprise Security</span>
            <h2 id="security-heading" className={styles.pipeline__heading}>
              Built for trust, at every layer.
            </h2>
            <p className={styles.pipeline__sub}>
              All transaction data is handled in strict compliance with global security regulations.
            </p>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "var(--space-4)" }}>
            {[
              { icon: "🔒", title: "AES-256 Encryption", desc: "Data encrypted at rest and TLS 1.3 in transit with Perfect Forward Secrecy." },
              { icon: "👁️", title: "Read-Only POS Access", desc: "Integration modules only request read permissions. We cannot modify pricing or inventory." },
              { icon: "🔑", title: "PII Hashing at Edge", desc: "Customer contacts are SHA-256 hashed at our edge gateway before reaching databases." },
              { icon: "✅", title: "SOC 2 Type II", desc: "Independent annual audits verify our operational security controls." },
            ].map((spec) => (
              <motion.div
                key={spec.title}
                className={styles.integrations__card}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.5 }}
              >
                <div className={styles.integrations__cardIcon}>{spec.icon}</div>
                <div className={styles.integrations__cardName}>{spec.title}</div>
                <div className={styles.integrations__cardDesc}>{spec.desc}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing Model ── */}
      <section id="pricing" className={styles.close} aria-labelledby="pricing-heading">
        <div className="container" style={{ position: "relative" }}>
          <span className="eyebrow" style={{ justifyContent: "center", display: "flex", marginBottom: "var(--space-4)" }}>
            Aligned Incentives
          </span>
          <h2 id="pricing-heading" className={styles.close__heading}>
            The platform is free.{" "}
            <em style={{ fontStyle: "italic", color: "var(--clay)" }}>
              We earn only when you grow.
            </em>
          </h2>
          <p style={{ maxWidth: "52ch", margin: "0 auto var(--space-8)", fontSize: "var(--text-base)", color: "var(--ink-muted)", lineHeight: "1.75", textAlign: "center" }}>
            No SaaS fees, no user seats, no data pipeline charges. Cocomo Engine only collects a success-based percentage of the incremental revenue we demonstrably drive for your outlets.
          </p>
          <Link href="/demo" className={styles.close__cta} id="platform-close-cta">
            Book a free demo
            <ArrowRight size={16} />
          </Link>
        </div>
      </section>
    </div>
  );
}
