"use client";

import React, { Suspense, useRef } from "react";
import dynamic from "next/dynamic";
import { motion, useScroll, useTransform } from "framer-motion";
import { Loop } from "../sections/Loop";
import { Cpu, Eye, Zap, BarChart4, Database, TrendingUp, Sparkles, MessageSquare } from "lucide-react";
import styles from "./platform.module.css";

// Lazy-load the custom interactive Engine Pipeline Canvas
const EnginePipelineCanvas = dynamic(
  () => import("@/components/media/EnginePipelineCanvas").then((m) => m.EnginePipelineCanvas),
  {
    ssr: false,
    loading: () => (
      <div className={styles.pipeline__fallback} aria-hidden="true">
        <div className={styles.pipeline__static} />
      </div>
    ),
  }
);

const phases = [
  {
    num: "01",
    title: "Observe Signals",
    icon: Eye,
    body: "Cocomo Engine connects directly to your Point of Sale (POS) system, foot-traffic telemetry, Meta ad accounts, Google reviews, and local weather indices. It observes hourly sales data, repeat visit cycles, and competitive pricing dynamically.",
    statVal: "POS & Ads",
    statLabel: "Real-time Connectors",
    color: "#2563EB"
  },
  {
    num: "02",
    title: "Recommend Actions",
    icon: Cpu,
    body: "Instead of raw charts, our intelligence layers rank growth opportunities by projected ₹ impact, execution difficulty, and statistical confidence. You get clear, plainspoken recommendations for your outlet.",
    statVal: "AI Ranked",
    statLabel: "Revenue Recommendations",
    color: "#00B4D8"
  },
  {
    num: "03",
    title: "Execute Seamlessly",
    icon: Zap,
    body: "One click triggers campaign execution. The engine orchestrates creators (via Cocomo Media), launches hyper-local Meta ad sets, pushes tailored WhatsApp re-engagement loops, or triggers internal staff task workflows automatically.",
    statVal: "1-Click",
    statLabel: "Execution Dispatch",
    color: "#2563EB"
  },
  {
    num: "04",
    title: "Measure Impact",
    icon: BarChart4,
    body: "No vanity metrics or estimated impressions. Every campaign is tracked back to outlet-level transactions. We prove the exact incremental revenue lift generated by each recommendation.",
    statVal: "₹ Verified",
    statLabel: "Transaction-level Lift",
    color: "#00B4D8"
  },
];

interface StackPhaseCardProps {
  num: string;
  title: string;
  body: string;
  icon: React.ComponentType<{ size: number; color?: string }>;
  statVal: string;
  statLabel: string;
  color: string;
  index: number;
}

function StackPhaseCard({ num, title, body, icon: Icon, statVal, statLabel, color, index }: StackPhaseCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: cardRef,
    offset: ["start end", "start 110px"]
  });

  const scale = useTransform(scrollYProgress, [0.5, 1], [1, 1 - index * 0.03]);
  const opacity = useTransform(scrollYProgress, [0.5, 1], [1, 1 - index * 0.1]);
  const rotateX = useTransform(scrollYProgress, [0.5, 1], [0, index * -2.5]);

  return (
    <motion.div
      ref={cardRef}
      className={styles.phaseCard}
      style={{
        scale,
        opacity,
        rotateX,
        perspective: 1000
      }}
    >
      <div className={styles.phaseCard__left}>
        <span className={styles.phaseCard__num}>{num}</span>
        <h3 className={styles.phaseCard__title}>{title}</h3>
        <p className={styles.phaseCard__body}>{body}</p>
        
        <div className={styles.phaseCard__stat}>
          <span style={{ fontSize: "1.75rem", fontWeight: 700, color, fontFamily: "serif" }}>{statVal}</span>
          <div style={{ fontSize: "10px", color: "rgba(10, 22, 47, 0.6)", marginTop: "2px" }}>{statLabel}</div>
        </div>
      </div>
      <div className={styles.phaseCard__right}>
        <div className={styles.phaseCard__iconWrapper} style={{ background: `rgba(${color === "#2563EB" ? "37,99,235" : "0,180,216"}, 0.08)`, border: `1px dashed ${color}` }}>
          <Icon size={32} color={color} />
        </div>
      </div>
    </motion.div>
  );
}

export default function PlatformPage() {
  return (
    <div className={styles.page}>
      {/* Hero */}
      <section className={styles.hero} aria-labelledby="platform-heading">
        <div className={styles.hero__glow} aria-hidden="true" />
        <div className={`container ${styles.hero__inner}`}>
          <div className={styles.hero__copy}>
            <span className="eyebrow" style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}>
              <Cpu size={12} color="#2563EB" />
              COCOMO ENGINE PLATFORM
            </span>
            <h1 id="platform-heading" className={styles.hero__heading}>
              A growth engine, not a dashboard.
            </h1>
            <p className={styles.hero__sub}>
              Cocomo Engine is the missing growth layer. It continuously connects POS telemetry to real-world creator campaign and digital advertising actions, delivering verifiable revenue lift.
            </p>
          </div>
          
          <div className={styles.hero__graphic}>
            <Suspense fallback={null}>
              <EnginePipelineCanvas />
            </Suspense>
          </div>
        </div>
      </section>

      {/* Loop diagram */}
      <Loop />

      {/* Four phases detail with 3D Stacking effects */}
      <section id="loop" className={styles.phases} aria-labelledby="phases-heading">
        <div className="container">
          <div className={styles.phases__header}>
            <span className="eyebrow">Product Pipeline</span>
            <h2 id="phases-heading" className={styles.phases__heading}>
              Continuous closed-loop growth.
            </h2>
            <p className={styles.phases__sub}>Scroll down to see the continuous loop engine operate phase-by-phase.</p>
          </div>
          
          <div className={styles.phases__stackList}>
            {phases.map((phase, idx) => (
              <StackPhaseCard
                key={phase.num}
                num={phase.num}
                title={phase.title}
                body={phase.body}
                icon={phase.icon}
                statVal={phase.statVal}
                statLabel={phase.statLabel}
                color={phase.color}
                index={idx}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Pricing model */}
      <section id="pricing" className={styles.pricing} aria-labelledby="pricing-heading">
        <div className="container">
          <div className={styles.pricing__inner}>
            <span className="eyebrow" style={{ color: "#2563EB" }}>ALIGNED INCENTIVES</span>
            <h2 id="pricing-heading" className={styles.pricing__heading}>
              The platform is free.
              <br />
              We earn only when you grow.
            </h2>
            <p className={styles.pricing__body}>
              We do not charge SaaS subscription fees, user seats, or data pipeline charges. Cocomo Engine only collects a success-based percentage of the incremental revenue we demonstrably drive for your outlets, measured against your baseline transaction data.
            </p>
          </div>
        </div>
      </section>

      {/* Security */}
      <section id="security" className={styles.security} aria-labelledby="security-heading" style={{ borderTop: "1px solid var(--hairline)", paddingBlock: "5rem", background: "rgba(246, 248, 252, 0.3)" }}>
        <div className="container">
          <div className={styles.security__inner} style={{ display: "grid", gridTemplateColumns: "1fr", gap: "2.5rem" }}>
            <div>
              <h2 id="security-heading" className={styles.security__title} style={{ fontSize: "1.75rem", fontWeight: 600, color: "var(--ink)", marginBottom: "1rem", fontFamily: "var(--font-serif)" }}>Enterprise Security</h2>
              <p className={styles.security__body} style={{ fontSize: "0.9375rem", color: "var(--ink-soft)", lineHeight: 1.6, maxWidth: "60ch" }}>
                All transaction data is handled in strict compliance with global security regulations. Cocomo Engine connects to your POS via read-only APIs with scoped access permissions.
              </p>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "2rem", marginTop: "1rem" }}>
              {[
                { title: "Military-Grade Encryption", desc: "Data is encrypted using AES-256 at rest and TLS 1.3 in transit with Perfect Forward Secrecy." },
                { title: "Scoped Read-Only Access", desc: "Our POS integration modules only request read permissions for order history. We cannot modify pricing or inventory." },
                { title: "PII Hashing at Edge", desc: "Customer phone numbers and emails are instantly hashed using SHA-256 at our edge gateway before reaching our databases." },
                { title: "SOC 2 Type II Certified", desc: "Independent annual third-party audits verify our operational security controls and data safety policies." }
              ].map((spec) => (
                <div key={spec.title} style={{ background: "#FFFFFF", border: "1px solid rgba(10, 22, 47, 0.06)", padding: "1.5rem", borderRadius: "14px", boxShadow: "0 4px 12px rgba(10,22,47,0.01)" }}>
                  <h3 style={{ fontSize: "1rem", fontWeight: 600, color: "var(--ink)", marginBottom: "0.5rem" }}>{spec.title}</h3>
                  <p style={{ fontSize: "0.8125rem", color: "var(--ink-soft)", lineHeight: 1.5 }}>{spec.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
